# Generated by Django 3.1.1 on 2020-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='source_code',
            field=models.CharField(max_length=100000000000000000000000000000000),
        ),
    ]
