# Generated by Django 3.1.1 on 2020-09-24 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200924_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner',
            new_name='author',
        ),
        migrations.AddField(
            model_name='note',
            name='password_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='r_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='rw_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.CharField(max_length=16),
        ),
    ]
