version: "3"

services:
    postgres:
        restart: always
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - config/.env
    redis:
        restart: always
        image: redis:latest
        volumes:
            - redisdata:/data
    codeo:
        restart: always
        build:
            context: .
            dockerfile: config/Dockerfile
        command: sh -c "./config/initdb.sh &&
                        python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app/
        ports:
            - 8000:8000
        env_file:
            - config/.env
        depends_on:
            - postgres
            - redis

volumes:
    postgres_data:
    redisdata: