version: "3"

services:
    postgres:
        restart: always
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - config/.env
    redis:
        restart: always
        image: redis:latest
        volumes:
            - redisdata:/data
    codeo:
        restart: always
        build:
            context: .
            dockerfile: config/Dockerfile
        command: sh -c "./config/initdb.sh &&
                        gunicorn --bind 0.0.0.0:8000 codeo.wsgi"
        volumes:
            - .:/app/
        expose:
            - 8000
        env_file:
            - config/.env
        depends_on:
            - postgres
            - redis
    nginx:
        build: ./config/nginx
        volumes:
        - ./staticfiles:/app/staticfiles
        ports:
        - 80:80
        depends_on:
        - codeo

volumes:
    postgres_data:
    redisdata: